
version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
    build:
      executor: android/android

      steps:
        - checkout
        - run:
            name: chmod permissions
            command: chmod +x ./gradlew

        - run:
            name: Build project
            command: ./gradlew build



