# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  android: circleci/android@2.3.0



# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
    build:
      docker:
        - image: cimg/base:stable
      executor:
        name: android/android

      steps:
        - checkout
        - run:
            name: chmod permissions
            command: chmod +x ./gradlew
        - run:
            name: Run Tests
            command: ./gradlew lint test
        - store_artifacts:
            path: app/build/reports
            destination: reports
        - store_test_results:
            path: app/build/test-results




# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - build
